### ISSUE TITLE
uninitialized constant CamaleonCms::TermTaxonomy with version 0.2

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-ecommerce#12]
I am getting below error if I use camaleon-ecommerce plugin 0.2

```
uninitialized constant CamaleonCms::TermTaxonomy

Application Trace | Framework Trace | Full Trace

/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-ecommerce-e6f473f83936/app/models/plugins/ecommerce/order.rb:9:in `<top (required)>'
/Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-ecommerce-e6f473f83936/app/helpers/plugins/ecommerce/ecommerce_helper.rb:170:in `ecommerce_on_active'
camaleon_cms (1.0.6) app/helpers/hooks_helper.rb:46:in `rescue in block in _do_hook'
camaleon_cms (1.0.6) app/helpers/hooks_helper.rb:41:in `block in _do_hook'
```

I installed this plugin as gem by adding to Gemfile, but 0.1 version plugin was working without any issues

**Comment by mazharoddin** [comment]
After this error site is become unusable with below error.

```
uninitialized constant CamaleonCms::Site

      next unless app["path"].present?
      s = File.join(app["path"], "config", "custom_models.rb")
      eval(File.read(s)) if File.exist?(s)
    }
  end

camaleon_cms (1.0.6) app/helpers/site_helper.rb:124:in `eval'
camaleon_cms (1.0.6) app/helpers/site_helper.rb:124:in `eval'
camaleon_cms (1.0.6) app/helpers/site_helper.rb:124:in `block in site_load_custom_models'
```

Due to this error I am unable to access the site now

**Comment by raulanatol** [comment]
Hi @mazharoddin!

CamaleonCms::Site it's a constant of the camaleon_cms version 2. 
Please test with this camaleon_cms version.

Regards.

**Comment by mazharoddin** [comment]
Hi Raul,
Yes, I am using camaleon_cms version 2, but still I am getting same error. Thanks.

**Comment by mazharoddin** [comment]
Hi Raulanatol,
I could resolve this issue by adding version info in Gemfile like below 

```
gem 'camaleon_cms', '~> 2'
```

Now issue got resolved, thank you.

**Comment by raulanatol** [comment]
Hi @mazharoddin!

Feels good to hear!

Regards.

**Comment by mazharoddin** [comment]
Hi Raulanatol,
Thanks for the help!! :)
